---
title: "ImputaionData"
author: "Jiaxin Shi"
date: "1/10/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load libraries
```{r}
library(dplyr)
```

## Data Simulation

```{r}
set.seed(42)
n = 10000
x1 = rnorm(n)
x2 = rnorm(n)
x3 = rnorm(n)
x = matrix(c(x1,x2,x3), nrow = n)
```

```{r}
# data transformation
bin_continuous = function(data, num_bins){
  data = data.frame(cont = data)
  new_data = data %>% transmute(disc = cut(cont, 
                                           breaks = unique(quantile(cont, 
                                                                    probs = seq.int(0,1,by = 1/num_bins))),
                                           labels = seq(0,num_bins-1, by = 1),
                                           include.lowest = TRUE))
  return(as.numeric(levels(new_data$disc))[new_data$disc])
}
```


### data1: y = b1x1 + b2x2 + b3x3

```{r}
b1 = c(1,1,3)
e1 = rnorm(n)
y1 = x %*% b1 + e1
range(y1)
```

```{r}
# output data for other imputation method
data1 = data.frame(x1 = bin_continuous(x1,3), 
                  x2 = bin_continuous(x2,2), 
                  x3 = bin_continuous(x3,3), 
                  z = bin_continuous(y1,4))
write.csv(data1, file = './data/sim_1.csv')

```

### data2: y = x1 + x2^2 + exp(x3)
```{r}
e2 = rnorm(n)
y2 = x1 + x2^2 + exp(x3) + x1*x2 + x2*x3 + e2
range(y2)
```

```{r}
# output data for other imputation method
data2 = data.frame(x1 = bin_continuous(x1,3), 
                  x2 = bin_continuous(x2,2), 
                  x3 = bin_continuous(x3,3),
                  z = bin_continuous(y2,4))
write.csv(data2, file = './data/sim_2.csv')
```

## Different set of conditional distributions
```{r}
# re-generate data
set.seed(42)
n = 10000
x1 = rnorm(n)
x2 = rnorm(n)
x3 = rnorm(n)
x4 = rnorm(n)
x5 = rnorm(n)
x = matrix(c(x1,x2,x3,x4,x5), nrow = n)
```

### data3: y = x1^2 + exp(x2+x3/3) + sin(x4+x5)
```{r}
# generate y1
e1 = rnorm(n)
y1 = x1^2 + exp(x2 + x3/3) + sin(x4+x5)+e1
range(y1)
```

```{r}
# output data for other imputation method
data1 = data.frame(x1 = bin_continuous(x1,3), 
                  x2 = bin_continuous(x2,2), 
                  x3 = bin_continuous(x3,3),
                  x4 = bin_continuous(x4, 5),
                  x5 = bin_continuous(x5, 3),
                  z = y1)
str(data1)
write.csv(data1, file = './data/sim_m1.csv', row.names = F)
```



### data4: y = x1^2+exp(x2+x3/3)+x4-x5+(0.5+x2^2/2+x5^2/2)*e
```{r}
# generate y2
e2 = rnorm(n)
y2 = x1^2+exp(x2+x3/3)+x4-x5+(0.5+x2^2/2+x5^2/2)*e2
range(y2)
```

```{r}
# output data for other imputation method
data2 = data.frame(x1 = bin_continuous(x1,3), 
                  x2 = bin_continuous(x2,2), 
                  x3 = bin_continuous(x3,3),
                  x4 = bin_continuous(x4, 5),
                  x5 = bin_continuous(x5, 3),
                  z = y2)
str(data2)
write.csv(data2, file = './data/sim_m2.csv', row.names = F)
```



### data5: y = (5+x1^2/3 + x2^2 + x3^3 +x4+x5)*exp(0.5*e)

```{r}
# generate y3 (multiplicative non-Gaussian error term)
norm_var1 = rnorm(n,-2,1)
norm_var2 = rnorm(n,2,1)
unif_var = runif(n)
e3 = as.numeric(unif_var < 0.5) * norm_var1 + as.numeric(unif_var >= 0.5) * norm_var2
y3 = (5+x1^2/3 + x2^2 + x3^3 + x4 + x5)*exp(0.5*e3)
range(y3)
```

```{r}
# output data for other imputation method
data3 = data.frame(x1 = bin_continuous(x1,3), 
                  x2 = bin_continuous(x2,2), 
                  x3 = bin_continuous(x3,3),
                  x4 = bin_continuous(x4,5),
                  x5 = bin_continuous(x5,3),
                  z = y3)
str(data3)
write.csv(data3, file = './data/sim_m3.csv', row.names = F)
```

### data6: y = I(u<0.5)*N(-x1, 0.25^2) + I(u>0.5)*N(x1, 0.25^2)

```{r}
# generate y4 (mixture of two normal distribution)
unif_var = runif(n)
norm_var = bin_continuous(x1, 3)
y4 = as.numeric(unif_var <0.5) * rnorm(n, norm_var*-1, 0.25^2) + as.numeric(unif_var >= 0.5) * rnorm(n, norm_var, 0.25^2)
range(y4)
```

```{r}
# output data for other imputation method
data4 = data.frame(x1 = bin_continuous(x1,3), 
                  x2 = bin_continuous(x2,2), 
                  x3 = bin_continuous(x3,3),
                  x4 = bin_continuous(x4,5),
                  x5 = bin_continuous(x5,3),
                  z = y4)
str(data4)
write.csv(data4, file = './data/sim_m4.csv', row.names = F)
```